package domain

import "github.com/google/uuid"

// ID is the Todo's identity. Wrapping it in a named type means you can never
// accidentally pass a UserID where a TodoID belongs -- a whole class of bug
// that string-typed IDs allow and that Go's type system eliminates for free.
//
// Identity is generated by the APPLICATION, not by Postgres. A DDD entity has
// identity from the moment it is constructed, before anything is persisted.
type ID struct {
	value string
}

// NewID mints a brand-new identity.
func NewID() ID {
	return ID{value: uuid.NewString()}
}

// ParseID rebuilds an ID from a string arriving over HTTP or out of Postgres.
//
// The parsed value is re-serialised rather than kept verbatim, so casing and
// formatting are normalised -- "ABC-..." and "abc-..." become one canonical
// form and cannot produce two IDs that are Equal-but-not-equal.
func ParseID(value string) (ID, error) {
	parsed, err := uuid.Parse(value)
	if err != nil {
		return ID{}, ErrInvalidID
	}
	return ID{value: parsed.String()}, nil
}

func (id ID) String() string   { return id.value }
func (id ID) IsZero() bool     { return id.value == "" }
func (id ID) Equals(o ID) bool { return id.value == o.value }
