package domain

// ID is the Todo's identity. Wrapping it in a named type means you can never
// accidentally pass a UserID where a TodoID belongs -- a whole class of bug
// that string-typed IDs allow and that Go's type system can eliminate for free.
//
// Storage choice: UUID (generated by the app) vs bigserial (generated by
// Postgres). UUID keeps identity generation inside the domain, which is the
// DDD-correct answer -- an entity should have identity before it is saved.
type ID struct {
	value string
}

// NewID mints a brand-new identity.
//
// TODO(you): generate a UUID. Add github.com/google/uuid to go.mod, or use
// crypto/rand if you want to stay dependency-free.
func NewID() ID {
	return ID{} // TODO
}

// ParseID rebuilds an ID from a string coming in over HTTP or out of Postgres.
//
// TODO(you): validate the format, return ErrInvalidID on failure.
func ParseID(value string) (ID, error) {
	return ID{}, nil // TODO
}

func (id ID) String() string      { return id.value }
func (id ID) IsZero() bool        { return id.value == "" }
func (id ID) Equals(o ID) bool    { return id.value == o.value }
